#!/bin/bash
# VocaNote 네이티브 macOS 앱 빌드 (Xcode 없이 swiftc + CLT)
set -euo pipefail
cd "$(dirname "$0")"

APP="VocaNote.app"
echo "▸ building $APP ..."

# 이전에 떠 있던 인스턴스 종료 — 안 그러면 open 이 옛 바이너리를 되살림(=검색 안 됨 착시)
pkill -x VocaNote 2>/dev/null && echo "  (기존 실행 인스턴스 종료함)" || true

# Supabase 설정 주입: 웹과 동일한 프로젝트로 동기화하도록 .env.local 에서 읽어 생성.
# (SupabaseConfig.swift 는 gitignore — anon key는 공개키라 바이너리 임베드는 안전)
ENVFILE=""
for f in .env.local ../.env.local ../.env; do [ -f "$f" ] && ENVFILE="$f" && break; done
SB_URL=""; SB_KEY=""
if [ -n "$ENVFILE" ]; then
  SB_URL=$(grep -E '^VITE_SUPABASE_URL=' "$ENVFILE" | head -1 | sed -E 's/^VITE_SUPABASE_URL=//' | tr -d '"'"'"'' | tr -d "'" | tr -d ' \r')
  SB_KEY=$(grep -E '^VITE_SUPABASE_ANON_KEY=' "$ENVFILE" | head -1 | sed -E 's/^VITE_SUPABASE_ANON_KEY=//' | tr -d '"'"'"'' | tr -d "'" | tr -d ' \r')
  echo "  (Supabase 설정 주입: $ENVFILE — url=${SB_URL:0:28}… key=${SB_KEY:0:6}…)"
else
  echo "  (⚠ .env.local 없음 — 동기화 비활성 상태로 빌드)"
fi
cat > Sources/SupabaseConfig.swift <<EOF
// AUTO-GENERATED by build.sh from .env.local — 커밋 금지 (gitignore)
enum SupabaseConfig {
    static let url = "$SB_URL"
    static let anonKey = "$SB_KEY"
    static var isConfigured: Bool { !url.isEmpty && !anonKey.isEmpty }
}
EOF

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp Info.plist "$APP/Contents/Info.plist"

# 번들 데이터(사전/약어/ktword)
cp Resources/wordlist.txt "$APP/Contents/Resources/"
cp Resources/abbreviations.json "$APP/Contents/Resources/"
cp Resources/ktword.json "$APP/Contents/Resources/"

# 앱 아이콘 (없으면 생성)
[ -f AppIcon.icns ] || (cd icon && ./make-icons.sh)
cp AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"

# 모든 Swift 소스 컴파일
swiftc -swift-version 5 -O \
  -o "$APP/Contents/MacOS/VocaNote" \
  Sources/*.swift \
  -framework Cocoa -framework SwiftUI -framework Carbon -framework ServiceManagement -framework AVFoundation -framework ApplicationServices -framework Security

# 로컬 실행용 ad-hoc 서명
codesign --force --sign - "$APP" >/dev/null 2>&1 || true

echo "✅ Built ./$APP"
echo ""

# 최신 빌드를 확실히 띄운다: 남아있는 옛 인스턴스를 한 번 더 종료 후 open.
# (open 은 실행 중인 번들을 되살리므로 open 직전에 반드시 종료해야 함)
pkill -x VocaNote 2>/dev/null && sleep 0.3 || true
open "$APP"
echo "▶︎ 실행함 — ⌥Space 검색 · ⌃⌥Space 선택 단어 조회 / 메뉴바 'V'"
